
var SCATTER04 = [ "SCATTER04" , {
  SCATTERRadius: 300,
  innerCircleSize: 1,
  outerCircleSize: 3,
  innerCircleColor: "009E73", //green
  outerCircleColor: "009E73",
  innerPointType: "rect", //circle,rect
  outerPointType: "circle", //circle,rect
  innerrectWidth: 2,
  innerrectHeight: 2,
  outerrectWidth: 10,
  outerrectHeight: 10,
  outerCircleOpacity: 1,
  random_data: 0,

} ,[
  {chr: "REL606", start: "9903",  name: "mogA/yaaH", genep: "molybdenum cofactor biosynthesis protein/conserved inner membrane protein associated with acetate transport", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "231968",  name: "aspU/dkgB", genep: "tRNA-Asp/2,5-diketo-D-gluconate reductase B", change: "T", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "235481",  name: "yafE/mltD", genep: "predicted S-adenosyl-L-methionine-dependent methyltransferase/predicted membrane-bound lytic murein transglycosylase D", change: "A", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "255578",  name: "dinB", genep: "DNA polymerase IV", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "273276",  name: "yagU", genep: "conserved inner membrane protein", change: "GGGG", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "278236",  name: "yagX", genep: "predicted aromatic compound dioxygenase", change: "CCC", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "284330",  name: "ykgM/eaeH", genep: "50S ribosomal protein L31/attaching and effacing protein, pathogenesis factor", change: "CC", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "314681",  name: "yahJ", genep: "deaminase", change: "A", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "327471",  name: "prpE/codB", genep: "predicted propionyl-CoA synthetase with ATPase domain/cytosine transporter", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "352278",  name: "frmR/yaiO", genep: "regulator protein that represses frmRAB operon/hypothetical protein", change: "GG", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "352377",  name: "frmR/yaiO", genep: "regulator protein that represses frmRAB operon/hypothetical protein", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "359174",  name: "yaiT", genep: "conserved hypothetical protein", change: "A", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "379321",  name: "yajF", genep: "fructokinase", change: "GG", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "390850",  name: "proY/malZ", genep: "predicted cryptic proline transporter/maltodextrin glucosidase", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "403036",  name: "ribD/ribH", genep: "fused diaminohydroxyphosphoribosylaminopyrimidine deaminase and 5-amino-6-(5-phosphoribosylamino) uracil reductase/riboflavin synthase subunit beta", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "429444",  name: "clpX/insL-2", genep: "ATP-dependent protease ATP-binding subunit/putative transposase insL for insertion sequence IS186", change: "GG", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "444809",  name: "glnK", genep: "nitrogen assimilation regulatory protein for GlnL, GlnE, and AmtB", change: "GGGG", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "500339",  name: "ylbH", genep: "conserved protein, rhs-like", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "730146",  name: "ybgP", genep: "predicted assembly protein", change: "T", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "769053",  name: "galM", genep: "galactose-1-epimerase (mutarotase)", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "794414",  name: "ECB_00734/ECB_00735", genep: "putative bacteriophage protein/hypothetical protein", change: "GG", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "794751",  name: "ECB_00735", genep: "hypothetical protein", change: "GGG", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "796560",  name: "ECB_00737/ECB_00738", genep: "hypothetical protein/hypothetical protein", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "796797",  name: "ECB_00738", genep: "hypothetical protein", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "830951",  name: "ybiI", genep: "hypothetical protein", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "835993",  name: "ybiO", genep: "predicted mechanosensitive channel", change: "T", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "877351",  name: "cmr", genep: "multidrug efflux system protein", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "901257",  name: "ECB_00845", genep: "hypothetical protein", change: "CC", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "917189",  name: "artJ", genep: "arginine transporter subunit", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "931278",  name: "ybjE", genep: "predicted transporter", change: "T", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "942886",  name: "clpA/serW", genep: "ATPase and specificity subunit of ClpA-ClpP ATP-dependent serine protease, chaperone activity/tRNA-Ser", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "970245",  name: "pflB", genep: "pyruvate formate lyase I", change: "T", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "977257",  name: "aroA/ycaL", genep: "3-phosphoshikimate 1-carboxyvinyltransferase/predicted peptidase with chaperone function", change: "T", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "998942",  name: "ycbB", genep: "predicted carboxypeptidase", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1021251",  name: "ycbF", genep: "predicted periplasmic pilini chaperone", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1069806",  name: "torS", genep: "hybrid sensory histidine kinase in two-component regulatory system with TorR", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1111966",  name: "insE-1/serX", genep: "putative transposase-related protein/tRNA-Ser", change: "GG", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1166061",  name: "fabG/acpP", genep: "3-oxoacyl-[acyl-carrier-protein] reductase/acyl carrier protein", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1236428",  name: "ycgB", genep: "hypothetical protein", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1245756",  name: "ycgY/treA", genep: "hypothetical protein/periplasmic trehalase", change: "A", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1357637",  name: "ycjJ/ycjK", genep: "putrescine importer/gamma-Glu-putrescine synthase", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1357663",  name: "ycjJ/ycjK", genep: "putrescine importer/gamma-Glu-putrescine synthase", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1391130",  name: "ycjZ", genep: "predicted DNA-binding transcriptional regulator", change: "A", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1469017",  name: "ydcH/rimL", genep: "hypothetical protein/ribosomal-protein-L7/L12-serine acetyltransferase", change: "T", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1496865",  name: "yncG", genep: "predicted enzyme", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1531243",  name: "yddO", genep: "D-ala-D-ala transporter subunit", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1570698",  name: "ydeU/ydeZ", genep: "b1509; conserved protein/AI2 transporter", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1618094",  name: "ECB_01528", genep: "antitermination protein Q homolog from lambdoid prophage DLP12", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1639002",  name: "ynfF", genep: "oxidoreductase subunit", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1701672",  name: "sodC", genep: "superoxide dismutase, Cu, Zn", change: "GG", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1730806",  name: "ydhV", genep: "predicted oxidoreductase", change: "AA", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1795815",  name: "celF/celD", genep: "cryptic phospho-beta-glucosidase, NAD(P)-binding/DNA-binding transcriptional dual regulator", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1799132",  name: "celA/osmE", genep: "N,N'-diacetylchitobiose-specific enzyme IIB component of PTS/DNA-binding transcriptional activator", change: "A", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1869128",  name: "yeaY/yeaZ", genep: "predicted lipoprotein/predicted peptidase", change: "T", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1895222",  name: "yebS", genep: "conserved inner membrane protein", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1915618",  name: "yebK", genep: "predicted DNA-binding transcriptional regulator", change: "A", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1937938",  name: "cutC/yecM", genep: "copper homeostasis protein/predicted metal-binding enzyme", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1977653",  name: "yedY", genep: "hypothetical protein", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1993266",  name: "amn", genep: "AMP nucleosidase", change: "CC", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2007567",  name: "ECB_01906", genep: "conserved hypothetical protein", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2017730",  name: "yeeF/yeeY", genep: "predicted amino-acid transporter/predicted DNA-binding transcriptional regulator", change: "GG", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2149202",  name: "molR", genep: "molybdate metabolism regulator", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2153825",  name: "yehI", genep: "hypothetical protein", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2161669",  name: "yehQ", genep: "hypothetical protein", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2199623",  name: "lysP", genep: "lysine transporter", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2226947",  name: "yejE", genep: "predicted oligopeptide transporter subunit", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2239749",  name: "yejO", genep: "predicted autotransporter outer membrane protein", change: "CCC", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2245571",  name: "ccmD", genep: "cytochrome c biogenesis protein", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2249525",  name: "napH", genep: "quinol dehydrogenase membrane component", change: "T", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2268994",  name: "atoC", genep: "fused response regulator of ato operon, in two-component system with AtoS: response regulator/sigma54 interaction protein", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2275349",  name: "yfaQ", genep: "hypothetical protein", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2276714",  name: "yfaS", genep: "putative membrane protein", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2283334",  name: "yfaA", genep: "hypothetical protein", change: "T", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2329538",  name: "elaD", genep: "predicted enzyme", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2363690",  name: "yfcF", genep: "predicted enzyme", change: "T", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2388502",  name: "yfcA", genep: "conserved inner membrane protein", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2406553",  name: "fadL/yfdF", genep: "long-chain fatty acid outer membrane transporter/putative DNA modification enzyme; b2345_1", change: "CC", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2445096",  name: "yfeO", genep: "hypothetical protein", change: "CCC", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2506607",  name: "narQ", genep: "sensory histidine kinase in two-component regulatory system with NarP (NarL)", change: "T", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2539696",  name: "uraA", genep: "uracil transporter", change: "T", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2602856",  name: "yphG", genep: "hypothetical protein", change: "CC", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2611165",  name: "yfhK", genep: "predicted sensory kinase in two-component system", change: "CCCC", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2680491",  name: "ECB_02511", genep: "ParB family protein", change: "A", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2721284",  name: "srlE", genep: "glucitol/sorbitol-specific enzyme IIB component of PTS", change: "GGG", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2752473",  name: "mutS", genep: "DNA mismatch repair protein", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2795471",  name: "ygcG", genep: "hypothetical protein", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2841962",  name: "mltA/metZ", genep: "membrane-bound lytic murein transglycosylase A/tRNA-Met", change: "A", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2842185",  name: "metW", genep: "tRNA-Met", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2858825",  name: "ppdA/thyA", genep: "hypothetical protein/thymidylate synthase", change: "A", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2880036",  name: "yqeF", genep: "acetyl-CoA acetyltransferase", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2885435",  name: "ygeR", genep: "Tetratricopeptide repeat transcriptional regulator", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2885510",  name: "ygeR", genep: "Tetratricopeptide repeat transcriptional regulator", change: "CCC", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2887059",  name: "xdhA", genep: "xanthine dehydrogenase, molybdenum binding subunit", change: "GGGG", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2889234",  name: "xdhB", genep: "xanthine dehydrogenase, FAD-binding subunit", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3006462",  name: "yafZ", genep: "conserved protein", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3035291",  name: "ECB_02836", genep: "hypothetical type II secretion protein GspF", change: "CCC", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3091884",  name: "yqhG", genep: "hypothetical protein", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3128052",  name: "yqiK/rfaE", genep: "hypothetical protein/fused heptose 7-phosphate kinase/heptose 1-phosphate adenyltransferase", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3169336",  name: "ygjP/ygjQ", genep: "predicted metal dependent hydrolase/predicted thioredoxin-like", change: "CCC", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3244240",  name: "nlpI/pnp", genep: "hypothetical protein/polynucleotide phosphorylase/polyadenylase", change: "CC", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3285419",  name: "yhbL", genep: "isoprenoid biosynthesis protein with amidotransferase-like domain", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3303793",  name: "dcuD", genep: "predicted transporter", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3317812",  name: "yhcS", genep: "predicted DNA-binding transcriptional regulator, efflux system", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3335376",  name: "yhdT", genep: "conserved inner membrane protein", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3351645",  name: "rrfD", genep: "5S ribosomal RNA", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3390749",  name: "gspJ", genep: "predicted general secretory pathway component, cryptic", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3553612",  name: "rhsB", genep: "rhsB element core protein RshB", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3582354",  name: "yhiS", genep: "hypothetical protein", change: "A", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3640019",  name: "yhjW", genep: "predicted metal dependent hydrolase", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3702457",  name: "yibJ", genep: "predicted Rhs-family protein", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3886900",  name: "mioC/asnC", genep: "flavodoxin/DNA-binding transcriptional dual regulator", change: "A", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3891544",  name: "yieN/kup", genep: "fused predicted transcriptional regulator: sigma54 activator protein/conserved protein/potassium transporter", change: "GG", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3922454",  name: "yifN/rep", genep: "b3777; conserved protein/DNA helicase and single-stranded DNA-dependent ATPase", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3942757",  name: "yifK", genep: "predicted transporter", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3981833",  name: "ECB_03710", genep: "putative permease", change: "T", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3988107",  name: "ECB_03716/ysgA", genep: "conserved hypothetical protein/predicted hydrolase", change: "A", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4081210",  name: "kdgT", genep: "2-keto-3-deoxygluconate permease", change: "GGGG", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4101871",  name: "ftsN", genep: "essential cell division protein", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4111718",  name: "metL", genep: "bifunctional aspartate kinase II/homoserine dehydrogenase II", change: "A", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4179767",  name: "yjaG/hupA", genep: "hypothetical protein/HU, DNA-binding transcriptional regulator, alpha subunit", change: "CCC", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4293177",  name: "phnP", genep: "carbon-phosphorus lyase complex accessory protein", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4345438",  name: "dcuA", genep: "C4-dicarboxylate antiporter", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4357597",  name: "ampC", genep: "beta-lactamase/D-alanine carboxypeptidase", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4384337",  name: "purA/yjeB", genep: "adenylosuccinate synthetase/predicted DNA-binding transcriptional regulator", change: "A", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4471806",  name: "yjgR", genep: "predicted ATPase", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4475811",  name: "idnT/idnO", genep: "L-idonate and D-gluconate transporter/gluconate 5-dehydrogenase", change: "GGG", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4477302",  name: "idnD", genep: "L-idonate 5-dehydrogenase, NAD-binding", change: "A", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4481275",  name: "intB/yjgW", genep: "predicted integrase/predicted protein", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4491372",  name: "ECB_04148", genep: "secondary glycine betaine transporter BetU", change: "C", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4528651",  name: "fimD/fimF", genep: "outer membrane usher protein, type 1 fimbrial synthesis/minor component of type 1 fimbriae", change: "G", type: "INS", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4542778",  name: "yjiJ", genep: "predicted inner membrane protein", change: "CC", type: "INS", noc: "", notes: "indel, ->"}
]
];
