name: gen_vis
channels:
  - bioconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - biopython=1.85
  - breseq=0.39.0
  - bcbio-gff=0.7.1
