
var SCATTER02 = [ "SCATTER02" , {
  SCATTERRadius: 300,
  innerCircleSize: 1,
  outerCircleSize: 3,
  innerCircleColor: "green",
  outerCircleColor: "#CC3399",
  innerPointType: "circle", //circle,rect
  outerPointType: "circle", //circle,rect
  innerrectWidth: 2,
  innerrectHeight: 2,
  outerrectWidth: 10,
  outerrectHeight: 10,
  outerCircleOpacity: 1,
  random_data: 0,

} ,[
  {chr: "REL606", start: "38191",  name: "carB/caiF", genep: "carbamoyl-phosphate synthase large subunit/DNA-binding transcriptional activator", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "90705",  name: "ilvH/fruR", genep: "acetolactate synthase small subunit/DNA-binding transcriptional dual regulator", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "133135",  name: "yacH", genep: "hypothetical protein", change: "3", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "242202",  name: "ECB_00212", genep: "hypothetical protein", change: "2", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "314488",  name: "yahJ", genep: "deaminase", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "340408",  name: "mhpR", genep: "DNA-binding transcriptional activator, 3HPP-binding", change: "2", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "440338",  name: "cof/ybaO", genep: "thiamin pyrimidine pyrophosphate hydrolase/predicted DNA-binding transcriptional regulator", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "474383",  name: "ybaL", genep: "predicted transporter with NAD(P)-binding Rossmann-fold domain", change: "9", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "620815",  name: "dsbG/ahpC", genep: "periplasmic disulfide isomerase/thiol-disulphide oxidase/alkyl hydroperoxide reductase, C22 subunit", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "640131",  name: "cspE/ccrB", genep: "cold shock protein E/camphor resistance protein CrcB", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "699973",  name: "potE", genep: "putrescine/proton symporter: putrescine/ornithine antiporter", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "705623",  name: "kdpD", genep: "fused sensory histidine kinase in two-component regulatory system with KdpE: signal sensing protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "748756",  name: "hrsA", genep: "fused 2-O-a-mannosyl-D-glycerate specific PTS enzymes: IIA component/IIB component/IIC component", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "798334",  name: "ECB_00739", genep: "hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "840856",  name: "glnH/dps", genep: "glutamine ABC transporter periplasmic protein/DNA protection during starvation conditions", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "889880",  name: "ECB_00829/ECB_00830", genep: "conserved hypothetical protein/hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "894876",  name: "ECB_00833/ECB_00834", genep: "Terminase, ATPase subunit/putative capsid scaffolding protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "917552",  name: "artJ/artM", genep: "arginine transporter subunit/arginine transporter subunit", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1019369",  name: "ycbT", genep: "predicted fimbrial-like adhesin protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1037343",  name: "ompA/sulA", genep: "outer membrane protein A (3a;II*;G;d)/SOS cell division inhibitor", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1069909",  name: "torS", genep: "hybrid sensory histidine kinase in two-component regulatory system with TorR", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1118314",  name: "csgD/csgB", genep: "DNA-binding transcriptional activator in two-component regulatory system/curlin nucleator protein, minor subunit in curli complex", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1296667",  name: "adhE", genep: "fused acetaldehyde-CoA dehydrogenase/iron-dependent alcohol dehydrogenase/pyruvate-formate lyase deactivase", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1332148",  name: "topA/cysB", genep: "DNA topoisomerase I/DNA-binding transcriptional dual regulator, O-acetyl-L-serine-binding", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1349564",  name: "fabI/ycjD", genep: "enoyl-(acyl carrier protein) reductase/hypothetical protein", change: "2", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1368411",  name: "pspE/ycjM", genep: "thiosulfate:cyanide sulfurtransferase (rhodanese)/predicted glucosyltransferase", change: "2", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1592123",  name: "ydeI", genep: "hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1609175",  name: "ybcW–[ECB_01526]", genep: "ybcW,gnsB,ynfN,ECB_01516,cspI,ydfP,ydfQ,ydfR,essQ,ECB_01522,ECB_01523,insE-4,insF-4,[ECB_01526]", change: "7554", type: "DEL", noc: "", notes: "deletion, ->"},
  {chr: "REL606", start: "1617945",  name: "ECB_01528", genep: "antitermination protein Q homolog from lambdoid prophage DLP12", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1673654",  name: "uidA/uidR", genep: "beta-D-glucuronidase/DNA-binding transcriptional repressor", change: "2", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1679988",  name: "add", genep: "adenosine deaminase", change: "2", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1691520",  name: "ydgR/gst", genep: "putative tripeptide transporter permease/glutathionine S-transferase", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1707566",  name: "lhr", genep: "predicted ATP-dependent helicase", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1709847",  name: "lhr", genep: "predicted ATP-dependent helicase", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1724662",  name: "ydhS", genep: "conserved protein with FAD/NAD(P)-binding domain", change: "2", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1734972",  name: "lpp/ynhG", genep: "murein lipoprotein/hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1746206",  name: "ydiJ/ydiK", genep: "predicted FAD-linked oxidoreductase/predicted inner membrane protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1752757",  name: "aroD/ydiF", genep: "3-dehydroquinate dehydratase/fused predicted acetyl-CoA:acetoacetyl-CoA transferase: alpha subunit/beta subunit", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1788777",  name: "ydjN", genep: "predicted transporter", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1794888",  name: "celF", genep: "cryptic phospho-beta-glucosidase, NAD(P)-binding", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1804195",  name: "astB", genep: "succinylarginine dihydrolase", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1815918",  name: "ynjC", genep: "fused transporter subunits of ABC superfamily: membrane components", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1883366",  name: "manZ/yobD", genep: "mannose-specific enzyme IID component of PTS/hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1964163",  name: "araF/yecI", genep: "L-arabinose transporter subunit/predicted ferritin-like protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "1995676",  name: "yeeN/asnW", genep: "hypothetical protein/tRNA-Asn", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2015711",  name: "yeeE", genep: "predicted inner membrane protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2100308",  name: "ogrK–[ECB_02013]", genep: "ogrK,yegZ,ECB_01989,ECB_01990,ECB_01991,ECB_01992,ECB_01993,ECB_01994,ECB_01995,ECB_01996,ECB_01997,ECB_01998,ECB_01999,ECB_02000,ECB_02001,ECB_02002,ECB_02003,ECB_02004,ECB_02005,ECB_02006,ECB_02007,ECB_02008,ECB_02009,ECB_02010,ECB_02011,ECB_02012,[ECB_02013]", change: "22146", type: "DEL", noc: "", notes: "deletion, ->"},
  {chr: "REL606", start: "2131466",  name: "gatY/fbaB", genep: "D-tagatose 1,6-bisphosphate aldolase 2, catalytic subunit/fructose-bisphosphate aldolase", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2195256",  name: "yeiG", genep: "predicted esterase", change: "2", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2316643",  name: "yfbH", genep: "hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2397508",  name: "yfcTU", genep: "predicted outer membrane export usher protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2397959",  name: "yfcTU", genep: "predicted outer membrane export usher protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2404153",  name: "yfcY/yfcZ", genep: "acetyl-CoA acetyltransferase/hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2419542",  name: "evgS", genep: "hybrid sensory histidine kinase in two-component regulatory system with EvgA", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2445097",  name: "yfeO", genep: "hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2493001",  name: "cchA", genep: "predicted carboxysome structural protein, ethanolamine utilization protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2519539",  name: "nlpB", genep: "lipoprotein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2543771",  name: "purN/ppk", genep: "phosphoribosylglycinamide formyltransferase/polyphosphate kinase", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2677710",  name: "ECB_02509", genep: "Fels-2 prophage protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2704796",  name: "ygaZ", genep: "predicted transporter", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2713717",  name: "serV/csrA", genep: "tRNA-Ser/carbon storage regulator", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2719337",  name: "ygaD/mltB", genep: "competence damage-inducible protein A/membrane-bound lytic murein transglycosylase B", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2721285",  name: "srlE", genep: "glucitol/sorbitol-specific enzyme IIB component of PTS", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2737742",  name: "hycI", genep: "protease involved in processing C-terminal end of HycE", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2785653",  name: "ygcS", genep: "predicted transporter", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2788806",  name: "ygcW/yqcE", genep: "predicted deoxygluconate dehydrogenase/predicted transporter", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2870729",  name: "aas/galR", genep: "2-acyl-glycerophospho-ethanolamine acyltransferase/DNA-binding transcriptional repressor", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2899662",  name: "yqeB", genep: "conserved protein with NAD(P)-binding Rossman fold", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2900728",  name: "yqeC", genep: "hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2997463",  name: "ECB_02798", genep: "conserved hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "2997916",  name: "ECB_02798", genep: "conserved hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3001676",  name: "flu", genep: "antigen 43 (Ag43) phase-variable biofilm formation autotransporter", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3016895",  name: "ECB_02817", genep: "KpsU protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3021896",  name: "ECB_02821", genep: "hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3024713",  name: "ECB_02825", genep: "Pyrophosphorylase", change: "430", type: "DEL", noc: "", notes: "deletion, ->"},
  {chr: "REL606", start: "3088379",  name: "yghB", genep: "conserved inner membrane protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3168964",  name: "ygjP", genep: "predicted metal dependent hydrolase", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3174018",  name: "ygjU", genep: "sodium:serine/threonine symporter", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3185049",  name: "yqjG/yhaH", genep: "predicted S-transferase/predicted inner membrane protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3191276",  name: "yhaO/tdcG", genep: "predicted transporter/L-serine dehydratase 3", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3240040",  name: "mtr", genep: "tryptophan transporter of high affinity", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3382527",  name: "gspA", genep: "general secretory pathway component, cryptic", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3512383",  name: "yhhX/yhhY", genep: "predicted oxidoreductase with NAD(P)-binding Rossmann-fold domain/predicted acetyltransferase", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3546164",  name: "nikB", genep: "nickel transporter subunit", change: "2", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3563958",  name: "yhiKL", genep: "hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3570568",  name: "yhiO/uspA", genep: "universal stress protein UspB/universal stress global response regulator", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3579065",  name: "gor/arsR", genep: "glutathione reductase/DNA-binding transcriptional repressor", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3583076",  name: "yhiS", genep: "hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3643384",  name: "yhjY", genep: "hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3715795",  name: "ECB_03460", genep: "putative adhesin", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3729141",  name: "yibQ", genep: "predicted polysaccharide deacetylase", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3754163",  name: "pyrE/rph", genep: "orotate phosphoribosyltransferase/ribonuclease PH", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3779760",  name: "ECB_03519", genep: "putative transcriptional regulator", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3810685",  name: "uhpA/ilvN", genep: "DNA-binding response regulator in two-component regulatory system wtih UhpB/acetolactate synthase small subunit", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3855490",  name: "yieF", genep: "chromate reductase, Class I, flavoprotein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3891076",  name: "yieN", genep: "fused predicted transcriptional regulator: sigma54 activator protein/conserved protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3894997",  name: "rbsD–[yieO]", genep: "rbsD,rbsA,rbsC,rbsB,rbsK,rbsR,[yieO]", change: "6165", type: "DEL", noc: "", notes: "deletion, ->"},
  {chr: "REL606", start: "3987265",  name: "ECB_03715", genep: "conserved hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "3987308",  name: "ECB_03715", genep: "conserved hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4028073",  name: "polA/yihA", genep: "DNA polymerase I/GTP-binding protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4038538",  name: "bipA/yihL", genep: "GTP-binding protein/predicted DNA-binding transcriptional regulator", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4283419",  name: "yjcR/yjcS", genep: "predicted membrane fusion protein of efflux pump/predicted alkyl sulfatase", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4331220",  name: "yjdJ/yjdK", genep: "predicted acyltransferase with acyl-CoA N-acyltransferase domain/hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4339562",  name: "cadC", genep: "DNA-binding transcriptional activator", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4373234",  name: "yjeF", genep: "predicted carbohydrate kinase", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4388208",  name: "yjfH/yjfI", genep: "23S rRNA (Gm2251)-methyltransferase/hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4462990",  name: "yjgN", genep: "conserved inner membrane protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4492819",  name: "yis2", genep: "protein similar to IS600 ORF2", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4504889",  name: "insB-25/ECB_04162", genep: "b4563(b4576); IS1 protein insB/hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4530139",  name: "fimH", genep: "minor component of type 1 fimbriae", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4537061",  name: "yjiC", genep: "hypothetical protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4537683",  name: "yjiC/yjiD", genep: "hypothetical protein/DNA replication/recombination/repair protein", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4558781",  name: "hsdS", genep: "specificity determinant for hsdM and hsdR", change: "1", type: "DEL", noc: "", notes: "indel, ->"},
  {chr: "REL606", start: "4621954",  name: "yjjX/gpmB", genep: "NTPase/phosphoglycerate mutase", change: "1", type: "DEL", noc: "", notes: "indel, ->"}
]
];
